import 'dart:typed_data';
import 'dart:ui';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:intl/intl.dart';
import 'package:lottie/lottie.dart';
import 'package:random_string/random_string.dart';
import 'package:rumah_jamur/models/models.dart';
import 'package:rumah_jamur/services/services.dart';
import 'package:rumah_jamur/utils/utils.dart';
import 'package:rumah_jamur/widgets/widgets.dart';
import 'package:spincircle_bottom_bar/modals.dart';
import 'package:spincircle_bottom_bar/spincircle_bottom_bar.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:qrscan/qrscan.dart' as scanner;
import 'package:permission_handler/permission_handler.dart';
import 'dart:ui' as ui;

part 'firstrun/login_screen.dart';
part 'home/home_screen.dart';
part 'home/profile_screen.dart';
part 'firstrun/register_screen.dart';
part 'firstrun/welcome_screen.dart';
part 'home/code_presensi.dart';
part 'information/success_screen.dart';
part 'home/dashboard_screen.dart';
part 'information/qr_view.dart';
part 'jadwal/list_presensi.dart';
part 'information/error_screen.dart';
part 'jadwal/list_peserta.dart';
part 'jadwal/detail_peserta.dart';
part 'information/izin_screen.dart';
