import 'dart:typed_data';
import 'dart:ui';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:get/get.dart';
import 'package:image_gallery_saver/image_gallery_saver.dart';
import 'package:intl/intl.dart';
import 'package:lottie/lottie.dart';
import 'package:random_string/random_string.dart';
import 'package:rumah_jamur/models/models.dart';
import 'package:rumah_jamur/services/services.dart';
import 'package:rumah_jamur/utils/utils.dart';
import 'package:rumah_jamur/widgets/widgets.dart';
import 'package:spincircle_bottom_bar/modals.dart';
import 'package:spincircle_bottom_bar/spincircle_bottom_bar.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:qrscan/qrscan.dart' as scanner;
import 'package:permission_handler/permission_handler.dart';
import 'dart:ui' as ui;

part 'login_screen.dart';
part 'home_screen.dart';
part 'profile_screen.dart';
part 'register_screen.dart';
part 'welcome_screen.dart';
part 'code_presensi.dart';
part 'success_screen.dart';
part 'dashboard_screen.dart';
part 'qr_generator_screen.dart';
part 'qr_view.dart';
part 'list_presensi.dart';
part 'error_screen.dart';
part 'list_peserta.dart';
part 'detail_peserta.dart';
part 'izin_screen.dart';
